services:
  api01: &api
    hostname: api01
    build: .
    # command: npx nodemon app.js
    # command: npx nodemon --inspect=0.0.0.0:9229 app.js
    environment:
      - DB_HOSTNAME=mongo
      - PORT=8080
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "120MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=rbe
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo.conf:/etc/mongo.conf:ro
    command: mongod --config /etc/mongo.conf
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "290MB" 

networks:
  default:
    driver: bridge